// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PTLavaCar.Models.Models;

public partial class LavaCarContext : DbContext
{
    public LavaCarContext(DbContextOptions<LavaCarContext> options)
        : base(options)
    {
    }
    public LavaCarContext() { }
    public virtual DbSet<Servicios> Servicios { get; set; }

    public virtual DbSet<Vehiculo> Vehiculo { get; set; }

    public virtual DbSet<Vehiculo_Servicio> Vehiculo_Servicio { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Vehiculo_Servicio>(entity =>
        {
            entity.HasOne(d => d.ID_ServicioNavigation).WithMany(p => p.Vehiculo_Servicio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Servicio");

            entity.HasOne(d => d.ID_VehiculoNavigation).WithMany(p => p.Vehiculo_Servicio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vehiculo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}