// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PTLavaCar.Models.Models;

public partial class Servicios
{
    [Key]
    public int ID_Servicio { get; set; }

    [Required]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public int Monto { get; set; }

    [InverseProperty("ID_ServicioNavigation")]
    public virtual ICollection<Vehiculo_Servicio> Vehiculo_Servicio { get; set; } = new List<Vehiculo_Servicio>();
}