// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PTLavaCar.Models.Models;

[Table("Vehiculo-Servicio")]
public partial class Vehiculo_Servicio
{
    [Key]
    [Column("ID_Vehiculo-Servicio")]
    public int ID_Vehiculo_Servicio { get; set; }

    public int ID_Servicio { get; set; }

    public int ID_Vehiculo { get; set; }

    [ForeignKey("ID_Servicio")]
    [InverseProperty("Vehiculo_Servicio")]
    public virtual Servicios ID_ServicioNavigation { get; set; }

    [ForeignKey("ID_Vehiculo")]
    [InverseProperty("Vehiculo_Servicio")]
    public virtual Vehiculo ID_VehiculoNavigation { get; set; }
}