// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PTLavaCar.Models.Models;

public partial class Vehiculo
{
    [Key]
    public int ID_Vehiculo { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Placa { get; set; }

    [Required]
    [Unicode(false)]
    public string Dueno { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Marca { get; set; }

    [InverseProperty("ID_VehiculoNavigation")]
    public virtual ICollection<Vehiculo_Servicio> Vehiculo_Servicio { get; set; } = new List<Vehiculo_Servicio>();
}